version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "15432:5432"
  redis:
    image: redis
    ports:
      - "16379:6379"
  app:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    env_file:
      - app.env
