FROM ruby:2.4-slim
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

RUN mkdir /app
WORKDIR /app
ADD Gemfile /app/Gemfile
ADD Gemfile.lock /app/Gemfile.lock
RUN bundle install
ADD . /app

EXPOSE 3000
RUN rm /app/tmp/pids/server.pid || true
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]